
{
  "name": "chaoscrypt",
  "version": "1.0.0",
  "description": "Chaos-based cryptography system",
  "main": "main.js",
  "scripts": {
    "start": "node main.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "three": "^0.128.0",
    "gsap": "^3.12.2"
  }
}
